name = str(input("Enter your name: "))
location = str(input("Enter your location: "))
print("Hello", name, "how is the weather in", location, '?')
age = int(input("Enter your age?: "))
print("Good to know that you are ", age, "years old")
